spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3307/toy?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: root
      connection-test-query: SELECT 1
#  jpa:
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        #        default_batch_size: 1000
#        show_sql: false
#        format_sql: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true # parse to mybatis snake and java camel variable

server:
  port: 8888

